
import React from 'react';
import {
  Home,
  Calendar,
  BookOpen,
  ListChecks,
  PlusSquare,
  Settings,
  Users,
  FileText,
  BarChart3,
  ShieldAlert,
  LogOut,
  Trophy,
  MessageSquare,
  User,
  GraduationCap,
  Clock,
  TrendingUp,
  ClipboardList,
  Database,
  MapPin,
  CalendarClock,
  UserPlus,
  FolderOpen,
  Activity,
  Bell,
  Key,
  Shield,
  Zap,
  Archive,
  Search,
  Download,
  Upload,
  Monitor,
  Layers,
  Tools,
  HelpCircle,
  Bookmark,
  Mail,
  Phone,
  Globe,
  Cpu,
  HardDrive,
  Wifi,
  Radio,
  Construction,
  Building,
  Car,
  School,
  UserCheck,
  UserX,
  BookOpenCheck,
  ClipboardCheck,
  FileCheck,
  FolderCheck,
  AlertCircle,
  CheckCircle,
  XCircle,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Edit,
  Trash,
  Plus,
  Minus,
  Save,
  RefreshCw,
  Filter,
  SortAsc,
  SortDesc,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  MapPin as MapPinIcon,
  BarChart,
  PieChart,
  LineChart,
  Target,
  Zap as ZapIcon,
  Layers as LayersIcon,
  Database as DatabaseIcon,
  Server,
  Cloud,
  Smartphone,
  Tablet,
  Monitor as MonitorIcon,
  Printer,
  Scanner,
  Camera,
  Video,
  Music,
  Image,
  File,
  Folder,
  Link,
  ExternalLink,
  Share,
  Copy,
  Paste,
  Cut,
  Undo,
  Redo,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  Move,
  ZoomIn,
  ZoomOut,
  Shuffle,
  Repeat,
  Play,
  Pause,
  Stop,
  SkipBack,
  SkipForward,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Mic,
  MicOff,
  Headphones,
  Speaker,
  Radio as RadioIcon,
  Tv,
  Gamepad2,
  Joystick,
  Dices,
  Puzzle,
  Gift,
  Heart,
  HeartHandshake,
  Star,
  Bookmark as BookmarkIcon,
  Flag,
  Tag,
  Tags,
  Hash,
  AtSign,
  DollarSign,
  Percent,
  Calculator,
  Ruler,
  Palette,
  Brush,
  Pipette,
  Pen,
  PenTool,
  Eraser,
  Highlighter,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Quote,
  List,
  ListOrdered,
  Indent,
  Outdent,
  Code,
  Code2,
  Terminal,
  Bug,
  Wrench,
  Hammer,
  Screwdriver,
  Nut,
  Bolt,
  Cog,
  Sliders,
  Gauge,
  Thermometer,
  Zap as ZapIcon2,
  Battery,
  BatteryLow,
  Plug,
  Power,
  PowerOff,
  Lightbulb,
  Flashlight,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  TreePine,
  Flower,
  Leaf,
  Seedling,
  Apple,
  Banana,
  Cherry,
  Grape,
  Orange,
  Strawberry,
  Carrot,
  Corn,
  Pizza,
  Coffee,
  Beer,
  Wine,
  IceCream,
  Cake,
  Cookie,
  Candy,
  Fish,
  Bird,
  Cat,
  Dog,
  Horse,
  Rabbit,
  Squirrel,
  Turtle,
  Butterfly,
  Bug as BugIcon,
  Ant,
  Bee,
  Spider,
  Snail,
  Shell,
  Gem,
  Crown,
  Medal,
  Trophy as TrophyIcon,
  Award,
  Ribbon,
  Rosette,
  ShieldCheck,
  ShieldX,
  ShieldAlert as ShieldAlertIcon,
  Siren,
  AlertTriangle,
  AlertCircle as AlertCircleIcon,
  Info,
  HelpCircle as HelpCircleIcon,
  MessageCircle,
  MessageSquare as MessageSquareIcon,
  Mail as MailIcon,
  Inbox,
  Send,
  Reply,
  ReplyAll,
  Forward,
  Archive as ArchiveIcon,
  Trash2,
  Spam,
  AtSign as AtSignIcon,
  Phone as PhoneIcon,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  Voicemail,
  MessageSquare as MessageSquareIcon2,
  Video as VideoIcon,
  Camera as CameraIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Headphones as HeadphonesIcon,
  Speaker as SpeakerIcon,
  Radio as RadioIcon2,
  Tv as TvIcon,
  Monitor as MonitorIcon2,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Laptop,
  PcCase,
  Keyboard,
  Mouse,
  Printer as PrinterIcon,
  Scanner as ScannerIcon,
  Fax,
  HardDrive as HardDriveIcon,
  Usb,
  Bluetooth,
  Wifi as WifiIcon,
  WifiOff,
  Rss,
  Globe as GlobeIcon,
  Link as LinkIcon,
  ExternalLink as ExternalLinkIcon,
  Share as ShareIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Cloud as CloudIcon,
  CloudDownload,
  CloudUpload,
  Server as ServerIcon,
  Database as DatabaseIcon2,
  FileText as FileTextIcon,
  File as FileIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  FilePlus,
  FolderPlus,
  FileCheck as FileCheckIcon,
  FolderCheck as FolderCheckIcon,
  FileX,
  FolderX,
  FileEdit,
  FileCopy,
  FileSearch,
  FileImage,
  FileVideo,
  FileAudio,
  FilePdf,
  FileSpreadsheet,
  FileCode,
  FileArchive,
  Briefcase,
  Package,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Wallet,
  Coins,
  DollarSign as DollarSignIcon,
  Euro,
  Pound,
  Yen,
  Banknote,
  Receipt,
  PiggyBank,
  TrendingUp as TrendingUpIcon,
  TrendingDown,
  BarChart as BarChartIcon,
  BarChart2,
  BarChart3 as BarChart3Icon,
  LineChart as LineChartIcon,
  PieChart as PieChartIcon,
  Activity as ActivityIcon,
  Pulse,
  Target as TargetIcon,
  Crosshair,
  Navigation,
  Compass,
  Map,
  MapPin as MapPinIcon2,
  Route,
  Car as CarIcon,
  Truck,
  Bus,
  Bike,
  Plane,
  Ship,
  Train,
  Rocket,
  Fuel,
  Construction as ConstructionIcon,
  Hammer as HammerIcon,
  Wrench as WrenchIcon,
  Screwdriver as ScrewdriverIcon,
  Paintbrush,
  Paintbrush2,
  Drill,
  Saw,
  Axe,
  Pickaxe,
  Shovel,
  Building as BuildingIcon,
  Building2,
  Home as HomeIcon,
  House,
  Store,
  Warehouse,
  Factory,
  Hospital,
  School as SchoolIcon,
  Church,
  Castle,
  Tent,
  TreePine as TreePineIcon,
  Mountain,
  Waves,
  Flame,
  Snowflake,
  Droplets,
  Wind,
  Tornado,
  Volcano,
  Earthquake,
  Sunrise,
  Sunset,
  MoonIcon,
  Stars,
  CloudRain as CloudRainIcon,
  CloudSnow as CloudSnowIcon,
  CloudLightning as CloudLightningIcon,
  Umbrella as UmbrellaIcon,
  Rainbow,
  Thermometer as ThermometerIcon,
  Gauge as GaugeIcon,
  Speedometer,
  Timer,
  Stopwatch,
  Clock as ClockIcon2,
  AlarmClock,
  Calendar as CalendarIcon2,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  CalendarClock as CalendarClockIcon,
  CalendarRange,
  CalendarHeart,
  Users as UsersIcon,
  User as UserIcon,
  UserPlus as UserPlusIcon,
  UserMinus,
  UserCheck as UserCheckIcon,
  UserX as UserXIcon,
  UserCog,
  UserSearch,
  UserEdit,
  UserDelete,
  Users2,
  Team,
  Crown as CrownIcon,
  Shield as ShieldIcon,
  Key as KeyIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Id,
  CreditCard as CreditCardIcon,
  Wallet as WalletIcon,
  Badge,
  Medal as MedalIcon,
  Trophy as TrophyIcon2,
  Award as AwardIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Surprised,
  Confused,
  Sleepy,
  Dizzy,
  Sick,
  Dead,
  Ghost,
  Alien,
  Robot,
  Baby,
  Child,
  Adult,
  Elderly,
  Man,
  Woman,
  Person,
  People,
  Family,
  Couple,
  Friends,
  Group,
  Crowd,
  Audience,
  Fans,
  Supporters,
  Followers,
  Subscribers,
  Members,
  Participants,
  Attendees,
  Guests,
  Visitors,
  Customers,
  Clients,
  Users as UsersIcon2,
  Accounts,
  Profiles,
  Contacts,
  Directory,
  AddressBook,
  PhoneBook,
  Notebook,
  Journal,
  Diary,
  Log,
  Record,
  Report,
  Document,
  Certificate,
  Diploma,
  License,
  Permit,
  Passport,
  Visa,
  Ticket,
  Pass,
  Card,
  Badge as BadgeIcon,
  Token,
  Chip,
  Barcode as BarcodeIcon,
  QrCode as QrCodeIcon,
  Scan as ScanIcon,
  Fingerprint as FingerprintIcon,
  Face,
  Retina,
  Voice,
  Signature,
  Handwriting,
  Stamp,
  Seal,
  Watermark,
  Logo,
  Brand,
  Icon,
  Symbol,
  Emoji,
  Sticker,
  GIF,
  Meme,
  Cartoon,
  Comic,
  Illustration,
  Drawing,
  Sketch,
  Painting,
  Artwork,
  Masterpiece,
  Gallery,
  Museum,
  Exhibition,
  Show,
  Display,
  Presentation,
  Demo,
  Preview,
  Sample,
  Example,
  Template,
  Pattern,
  Design,
  Layout,
  Structure,
  Framework,
  Architecture,
  Blueprint,
  Plan,
  Scheme,
  Strategy,
  Tactic,
  Method,
  Approach,
  Technique,
  Skill,
  Talent,
  Ability,
  Capability,
  Capacity,
  Potential,
  Power,
  Strength,
  Force,
  Energy,
  Vitality,
  Health,
  Fitness,
  Wellness,
  Medicine,
  Treatment,
  Therapy,
  Cure,
  Healing,
  Recovery,
  Rehabilitation,
  Exercise,
  Workout,
  Training,
  Practice,
  Rehearsal,
  Preparation,
  Study,
  Learning,
  Education,
  Teaching,
  Instruction,
  Guidance,
  Mentoring,
  Coaching,
  Tutoring,
  Supervision,
  Management,
  Leadership,
  Direction,
  Control,
  Command,
  Authority,
  Power as PowerIcon,
  Influence,
  Impact,
  Effect,
  Result,
  Outcome,
  Consequence,
  Achievement,
  Success,
  Victory,
  Win,
  Triumph,
  Accomplishment,
  Milestone,
  Goal,
  Objective,
  Target as TargetIcon2,
  Aim,
  Purpose,
  Mission,
  Vision,
  Dream,
  Aspiration,
  Ambition,
  Desire,
  Wish,
  Hope,
  Faith,
  Belief,
  Trust,
  Confidence,
  Assurance,
  Certainty,
  Security,
  Safety,
  Protection,
  Defense,
  Guard,
  Shield as ShieldIcon2,
  Armor,
  Helmet,
  Mask,
  Gloves,
  Boots,
  Uniform,
  Outfit,
  Costume,
  Clothing,
  Apparel,
  Fashion,
  Style,
  Trend,
  Design as DesignIcon,
  Art,
  Craft,
  Skill as SkillIcon,
  Technique as TechniqueIcon,
  Method as MethodIcon,
  Process,
  Procedure,
  Protocol,
  Standard,
  Norm,
  Rule,
  Regulation,
  Law,
  Policy,
  Guideline,
  Instruction as InstructionIcon,
  Manual,
  Handbook,
  Guide,
  Tutorial,
  Course,
  Lesson,
  Class,
  Session,
  Workshop,
  Seminar,
  Conference,
  Meeting,
  Discussion,
  Conversation,
  Dialogue,
  Interview,
  Survey,
  Poll,
  Vote,
  Election,
  Campaign,
  Promotion,
  Marketing,
  Advertising,
  Publicity,
  Announcement,
  News,
  Information,
  Data,
  Facts,
  Statistics,
  Analytics,
  Metrics,
  KPIs,
  Performance,
  Efficiency,
  Productivity,
  Quality,
  Excellence,
  Perfection,
  Optimization,
  Improvement,
  Enhancement,
  Upgrade,
  Update,
  Revision,
  Change,
  Modification,
  Adjustment,
  Customization,
  Configuration,
  Setup,
  Installation,
  Deployment,
  Launch,
  Release,
  Publication,
  Distribution,
  Delivery,
  Shipping,
  Transport,
  Logistics,
  Supply,
  Inventory,
  Stock,
  Storage,
  Warehouse as WarehouseIcon,
  Facility,
  Infrastructure,
  Equipment,
  Machinery,
  Technology,
  Innovation,
  Research,
  Development,
  Engineering,
  Science,
  Mathematics,
  Physics,
  Chemistry,
  Biology,
  Medicine as MedicineIcon,
  Psychology,
  Sociology,
  Anthropology,
  History,
  Geography,
  Literature,
  Language,
  Communication,
  Writing,
  Reading,
  Speaking,
  Listening,
  Understanding,
  Comprehension,
  Knowledge,
  Wisdom,
  Intelligence,
  Logic,
  Reasoning,
  Thinking,
  Analysis,
  Evaluation,
  Assessment,
  Judgment,
  Decision,
  Choice,
  Selection,
  Option,
  Alternative,
  Solution,
  Answer,
  Response,
  Reaction,
  Feedback,
  Comment,
  Opinion,
  View,
  Perspective,
  Angle,
  Point,
  Focus,
  Attention,
  Concentration,
  Dedication,
  Commitment,
  Responsibility,
  Accountability,
  Reliability,
  Trustworthiness,
  Honesty,
  Integrity,
  Ethics,
  Morality,
  Values,
  Principles,
  Standards as StandardsIcon,
  Criteria,
  Requirements,
  Specifications,
  Details,
  Features,
  Characteristics,
  Properties,
  Attributes,
  Qualities,
  Traits,
  Aspects,
  Elements,
  Components,
  Parts,
  Pieces,
  Fragments,
  Sections,
  Segments,
  Divisions,
  Categories,
  Types,
  Kinds,
  Varieties,
  Forms,
  Shapes,
  Sizes,
  Dimensions,
  Measurements,
  Quantities,
  Amounts,
  Numbers,
  Figures,
  Calculations,
  Computations,
  Operations,
  Functions,
  Procedures as ProceduresIcon,
  Processes as ProcessesIcon,
  Systems,
  Networks,
  Connections,
  Links,
  Relationships,
  Associations,
  Partnerships,
  Collaborations,
  Cooperations,
  Alliances,
  Unions,
  Mergers,
  Acquisitions,
  Investments,
  Funding,
  Finance,
  Budget,
  Cost,
  Price,
  Value,
  Worth,
  Benefit,
  Advantage,
  Profit,
  Revenue,
  Income,
  Earnings,
  Salary,
  Wage,
  Payment,
  Compensation,
  Reward,
  Incentive,
  Bonus,
  Prize,
  Gift as GiftIcon,
  Present,
  Offering,
  Donation,
  Contribution,
  Support,
  Help,
  Assistance,
  Aid,
  Service,
  Care,
  Attention as AttentionIcon,
  Love,
  Affection,
  Compassion,
  Empathy,
  Sympathy,
  Understanding as UnderstandingIcon,
  Patience,
  Tolerance,
  Acceptance,
  Forgiveness,
  Mercy,
  Grace,
  Kindness,
  Generosity,
  Charity,
  Altruism,
  Selflessness,
  Sacrifice,
  Dedication as DedicationIcon,
  Devotion,
  Loyalty,
  Faithfulness,
  Commitment as CommitmentIcon,
  Promise,
  Vow,
  Oath,
  Pledge,
  Contract,
  Agreement,
  Deal,
  Bargain,
  Negotiation,
  Settlement,
  Resolution,
  Solution as SolutionIcon,
  Fix,
  Repair,
  Restoration,
  Renewal,
  Revival,
  Resurrection,
  Rebirth,
  Transformation,
  Evolution,
  Progress,
  Advancement,
  Growth,
  Development as DevelopmentIcon,
  Expansion,
  Extension,
  Enlargement,
  Increase,
  Addition,
  Supplement,
  Extra,
  Bonus as BonusIcon,
  Premium,
  Upgrade as UpgradeIcon,
  Enhancement as EnhancementIcon,
  Improvement as ImprovementIcon,
  Betterment,
  Refinement,
  Polishing,
  Perfection as PerfectionIcon,
  Mastery,
  Expertise,
  Proficiency,
  Competence,
  Skill as SkillIcon2,
  Ability as AbilityIcon,
  Talent as TalentIcon,
  Gift as GiftIcon2,
  Blessing,
  Fortune,
  Luck,
  Chance,
  Opportunity,
  Possibility,
  Potential as PotentialIcon,
  Capacity as CapacityIcon,
  Capability as CapabilityIcon,
  Power as PowerIcon2,
  Strength as StrengthIcon,
  Force as ForceIcon,
  Energy as EnergyIcon,
  Vitality as VitalityIcon,
  Life,
  Existence,
  Being,
  Reality,
  Truth,
  Fact,
  Evidence,
  Proof,
  Verification,
  Validation,
  Confirmation,
  Approval,
  Authorization,
  Permission,
  License as LicenseIcon,
  Permit as PermitIcon,
  Access,
  Entry,
  Admission,
  Entrance,
  Gate,
  Door,
  Window,
  Opening,
  Portal,
  Gateway,
  Bridge,
  Connection as ConnectionIcon,
  Link as LinkIcon2,
  Relationship as RelationshipIcon,
  Bond,
  Tie,
  Attachment,
  Association as AssociationIcon,
  Partnership as PartnershipIcon,
  Collaboration as CollaborationIcon,
  Cooperation as CooperationIcon,
  Teamwork,
  Unity,
  Harmony,
  Balance,
  Equilibrium,
  Stability,
  Consistency,
  Reliability as ReliabilityIcon,
  Dependability,
  Trustworthiness as TrustworthinessIcon,
  Honesty as HonestyIcon,
  Integrity as IntegrityIcon,
  Ethics as EthicsIcon,
  Morality as MoralityIcon,
  Values as ValuesIcon,
  Principles as PrinciplesIcon,
  Standards as StandardsIcon2,
  Quality as QualityIcon,
  Excellence as ExcellenceIcon,
  Superiority,
  Distinction,
  Uniqueness,
  Originality,
  Creativity,
  Innovation as InnovationIcon,
  Invention,
  Discovery,
  Exploration,
  Investigation,
  Research as ResearchIcon,
  Study as StudyIcon,
  Analysis as AnalysisIcon,
  Examination,
  Inspection,
  Review,
  Evaluation as EvaluationIcon,
  Assessment as AssessmentIcon,
  Testing,
  Measurement,
  Calculation,
  Computation,
  Processing,
  Handling,
  Management as ManagementIcon,
  Administration,
  Governance,
  Leadership as LeadershipIcon,
  Direction as DirectionIcon,
  Guidance as GuidanceIcon,
  Supervision as SupervisionIcon,
  Oversight,
  Monitoring,
  Tracking,
  Following,
  Pursuing,
  Chasing,
  Hunting,
  Searching,
  Seeking,
  Finding,
  Discovering,
  Uncovering,
  Revealing,
  Exposing,
  Showing,
  Displaying,
  Presenting,
  Demonstrating,
  Illustrating,
  Explaining,
  Describing,
  Detailing,
  Specifying,
  Defining,
  Clarifying,
  Simplifying,
  Organizing,
  Arranging,
  Sorting,
  Categorizing,
  Classifying,
  Grouping,
  Clustering,
  Bundling,
  Packaging,
  Wrapping,
  Covering,
  Protecting,
  Securing,
  Safeguarding,
  Defending,
  Guarding,
  Watching,
  Observing,
  Seeing,
  Looking,
  Viewing,
  Examining as ExaminingIcon,
  Inspecting as InspectingIcon,
  Checking,
  Verifying as VerifyingIcon,
  Validating as ValidatingIcon,
  Confirming as ConfirmingIcon,
  Approving as ApprovingIcon,
  Accepting as AcceptingIcon,
  Agreeing,
  Consenting,
  Permitting as PermittingIcon,
  Allowing,
  Enabling,
  Facilitating,
  Supporting as SupportingIcon,
  Helping as HelpingIcon,
  Assisting as AssistingIcon,
  Aiding as AidingIcon,
  Serving as ServingIcon,
  Providing,
  Supplying,
  Delivering as DeliveringIcon,
  Offering as OfferingIcon,
  Giving,
  Sharing as SharingIcon,
  Contributing as ContributingIcon,
  Participating,
  Engaging,
  Involving,
  Including,
  Incorporating,
  Integrating,
  Combining,
  Merging as MergingIcon,
  Uniting as UnitingIcon,
  Joining,
  Connecting as ConnectingIcon,
  Linking as LinkingIcon,
  Bonding as BondingIcon,
  Attaching as AttachingIcon,
  Fastening,
  Securing as SecuringIcon,
  Locking as LockingIcon,
  Closing,
  Sealing as SealingIcon,
  Finishing,
  Completing,
  Ending,
  Concluding,
  Terminating,
  Stopping,
  Halting,
  Pausing,
  Resting,
  Relaxing,
  Unwinding,
  Calming,
  Soothing,
  Comforting,
  Reassuring,
  Encouraging,
  Motivating,
  Inspiring,
  Uplifting,
  Elevating,
  Raising,
  Lifting,
  Boosting,
  Enhancing as EnhancingIcon,
  Improving as ImprovingIcon,
  Upgrading as UpgradingIcon,
  Advancing as AdvancingIcon,
  Progressing as ProgressingIcon,
  Developing as DevelopingIcon,
  Growing as GrowingIcon,
  Expanding as ExpandingIcon,
  Extending as ExtendingIcon,
  Stretching,
  Reaching,
  Achieving as AchievingIcon,
  Accomplishing as AccomplishingIcon,
  Succeeding as SucceedingIcon,
  Winning as WinningIcon,
  Triumphing as TriumphingIcon,
  Conquering,
  Overcoming,
  Defeating,
  Beating,
  Surpassing,
  Exceeding,
  Outperforming,
  Excelling,
  Shining,
  Glowing,
  Radiating,
  Emanating,
  Emitting,
  Producing,
  Creating,
  Making,
  Building,
  Constructing as ConstructingIcon,
  Assembling,
  Manufacturing,
  Fabricating,
  Crafting as CraftingIcon,
  Designing as DesigningIcon,
  Planning as PlanningIcon,
  Organizing as OrganizingIcon,
  Arranging as ArrangingIcon,
  Preparing as PreparingIcon,
  Setting,
  Establishing,
  Founding,
  Starting,
  Beginning,
  Initiating,
  Launching as LaunchingIcon,
  Opening as OpeningIcon,
  Introducing,
  Presenting as PresentingIcon,
  Showing as ShowingIcon,
  Displaying as DisplayingIcon,
  Exhibiting,
  Demonstrating as DemonstratingIcon,
  Performing,
  Executing,
  Implementing,
  Applying,
  Using,
  Utilizing,
  Employing,
  Operating,
  Running,
  Working,
  Functioning,
  Serving as ServingIcon2,
  Acting,
  Behaving,
  Conducting,
  Managing as ManagingIcon,
  Handling as HandlingIcon,
  Dealing,
  Addressing,
  Tackling,
  Solving as SolvingIcon,
  Resolving as ResolvingIcon,
  Fixing as FixingIcon,
  Repairing as RepairingIcon,
  Restoring as RestoringIcon,
  Renewing as RenewingIcon,
  Refreshing,
  Revitalizing,
  Rejuvenating,
  Regenerating,
  Rebuilding,
  Reconstructing,
  Renovating,
  Remodeling,
  Refurbishing,
  Updating as UpdatingIcon,
  Upgrading as UpgradingIcon2,
  Modernizing,
  Advancing as AdvancingIcon2,
  Evolving as EvolvingIcon,
  Transforming as TransformingIcon,
  Converting,
  Changing as ChangingIcon,
  Modifying as ModifyingIcon,
  Adjusting as AdjustingIcon,
  Adapting,
  Customizing as CustomizingIcon,
  Personalizing,
  Tailoring,
  Fitting,
  Matching,
  Aligning,
  Coordinating,
  Synchronizing,
  Harmonizing,
  Balancing as BalancingIcon,
  Equalizing,
  Leveling,
  Standardizing,
  Normalizing,
  Regularizing,
  Stabilizing,
  Maintaining,
  Preserving,
  Conserving,
  Protecting as ProtectingIcon,
  Safeguarding as SafeguardingIcon,
  Defending as DefendingIcon,
  Securing as SecuringIcon2,
  Ensuring,
  Guaranteeing,
  Assuring,
  Promising as PromisingIcon,
  Committing as CommittingIcon,
  Dedicating as DedicatingIcon,
  Devoting,
  Investing,
  Contributing as ContributingIcon2,
  Participating as ParticipatingIcon,
  Engaging as EngagingIcon,
  Involving as InvolvingIcon,
  Including as IncludingIcon,
  Incorporating as IncorporatingIcon,
  Integrating as IntegratingIcon,
  Combining as CombiningIcon,
  Merging as MergingIcon2,
  Uniting as UnitingIcon2,
  Joining as JoiningIcon,
  Connecting as ConnectingIcon2,
  Linking as LinkingIcon2,
  Bonding as BondingIcon2,
  Attaching as AttachingIcon2,
  Fastening as FasteningIcon,
  Securing as SecuringIcon3,
  Locking as LockingIcon2,
  Closing as ClosingIcon,
  Sealing as SealingIcon2,
  Finishing as FinishingIcon,
  Completing as CompletingIcon,
  Ending as EndingIcon,
  Concluding as ConcludingIcon,
  Terminating as TerminatingIcon,
  Stopping as StoppingIcon,
  Halting as HaltingIcon,
  Pausing as PausingIcon,
  Resting as RestingIcon,
  Relaxing as RelaxingIcon,
  Unwinding as UnwindingIcon,
  Calming as CalmingIcon,
  Soothing as SoothingIcon,
  Comforting as ComfortingIcon,
  Reassuring as ReassuringIcon,
  Encouraging as EncouragingIcon,
  Motivating as MotivatingIcon,
  Inspiring as InspiringIcon,
  Uplifting as UpliftingIcon,
  Elevating as ElevatingIcon,
  Raising as RaisingIcon,
  Lifting as LiftingIcon,
  Boosting as BoostingIcon,
  Enhancing as EnhancingIcon2,
  Improving as ImprovingIcon2,
  Upgrading as UpgradingIcon3,
  Advancing as AdvancingIcon3,
  Progressing as ProgressingIcon2,
  Developing as DevelopingIcon2,
  Growing as GrowingIcon2,
  Expanding as ExpandingIcon2,
  Extending as ExtendingIcon2,
  Stretching as StretchingIcon,
  Reaching as ReachingIcon,
  Achieving as AchievingIcon2,
  Accomplishing as AccomplishingIcon2,
  Succeeding as SucceedingIcon2,
  Winning as WinningIcon2,
  Triumphing as TriumphingIcon2,
  Conquering as ConqueringIcon,
  Overcoming as OvercomingIcon,
  Defeating as DefeatingIcon,
  Beating as BeatingIcon,
  Surpassing as SurpassingIcon,
  Exceeding as ExceedingIcon,
  Outperforming as OutperformingIcon,
  Excelling as ExcellingIcon,
  Shining as ShiningIcon,
  Glowing as GlowingIcon,
  Radiating as RadiatingIcon,
  Emanating as EmanatingIcon,
  Emitting as EmittingIcon,
  Producing as ProducingIcon,
  Creating as CreatingIcon,
  Making as MakingIcon,
  Building as BuildingIcon2,
  Constructing as ConstructingIcon2,
  Assembling as AssemblingIcon,
  Manufacturing as ManufacturingIcon,
  Fabricating as FabricatingIcon,
  Crafting as CraftingIcon2,
  Designing as DesigningIcon2,
  Planning as PlanningIcon2,
  Organizing as OrganizingIcon2,
  Arranging as ArrangingIcon2,
  Preparing as PreparingIcon2,
  Setting as SettingIcon,
  Establishing as EstablishingIcon,
  Founding as FoundingIcon,
  Starting as StartingIcon,
  Beginning as BeginningIcon,
  Initiating as InitiatingIcon,
  Launching as LaunchingIcon2,
  Opening as OpeningIcon2,
  Introducing as IntroducingIcon,
  Presenting as PresentingIcon2,
  Showing as ShowingIcon2,
  Displaying as DisplayingIcon2,
  Exhibiting as ExhibitingIcon,
  Demonstrating as DemonstratingIcon2,
  Performing as PerformingIcon,
  Executing as ExecutingIcon,
  Implementing as ImplementingIcon,
  Applying as ApplyingIcon,
  Using as UsingIcon,
  Utilizing as UtilizingIcon,
  Employing as EmployingIcon,
  Operating as OperatingIcon,
  Running as RunningIcon,
  Working as WorkingIcon,
  Functioning as FunctioningIcon,
  Serving as ServingIcon3,
  Acting as ActingIcon,
  Behaving as BehavingIcon,
  Conducting as ConductingIcon,
  Managing as ManagingIcon2,
  Handling as HandlingIcon2,
  Dealing as DealingIcon,
  Addressing as AddressingIcon,
  Tackling as TacklingIcon,
  Solving as SolvingIcon2,
  Resolving as ResolvingIcon2,
  Fixing as FixingIcon2,
  Repairing as RepairingIcon2,
  Restoring as RestoringIcon2,
  Renewing as RenewingIcon2,
  Refreshing as RefreshingIcon,
  Revitalizing as RevitalizingIcon,
  Rejuvenating as RejuvenatingIcon,
  Regenerating as RegeneratingIcon,
  Rebuilding as RebuildingIcon,
  Reconstructing as ReconstructingIcon,
  Renovating as RenovatingIcon,
  Remodeling as RemodelingIcon,
  Refurbishing as RefurbishingIcon,
  Updating as UpdatingIcon2,
  Upgrading as UpgradingIcon4,
  Modernizing as ModernizingIcon,
  Advancing as AdvancingIcon4,
  Evolving as EvolvingIcon2,
  Transforming as TransformingIcon2,
  Converting as ConvertingIcon,
  Changing as ChangingIcon2,
  Modifying as ModifyingIcon2,
  Adjusting as AdjustingIcon2,
  Adapting as AdaptingIcon,
  Customizing as CustomizingIcon2,
  Personalizing as PersonalizingIcon,
  Tailoring as TailoringIcon,
  Fitting as FittingIcon,
  Matching as MatchingIcon,
  Aligning as AligningIcon,
  Coordinating as CoordinatingIcon,
  Synchronizing as SynchronizingIcon,
  Harmonizing as HarmonizingIcon,
  Balancing as BalancingIcon2,
  Equalizing as EqualizingIcon,
  Leveling as LevelingIcon,
  Standardizing as StandardizingIcon,
  Normalizing as NormalizingIcon,
  Regularizing as RegularizingIcon,
  Stabilizing as StabilizingIcon,
  Maintaining as MaintainingIcon,
  Preserving as PreservingIcon,
  Conserving as ConservingIcon,
  Protecting as ProtectingIcon2,
  Safeguarding as SafeguardingIcon2,
  Defending as DefendingIcon2,
  Securing as SecuringIcon4,
  Ensuring as EnsuringIcon,
  Guaranteeing as GuaranteeingIcon,
  Assuring as AssuringIcon,
  Promising as PromisingIcon2,
  Committing as CommittingIcon2,
  Dedicating as DedicatingIcon2,
  Devoting as DevotingIcon,
  Investing as InvestingIcon,
  Contributing as ContributingIcon3,
  Participating as ParticipatingIcon2,
  Engaging as EngagingIcon2,
  Involving as InvolvingIcon2,
  Including as IncludingIcon2,
  Incorporating as IncorporatingIcon2,
  Integrating as IntegratingIcon2,
  Combining as CombiningIcon2,
  Merging as MergingIcon3,
  Uniting as UnitingIcon3,
  Joining as JoiningIcon2,
  Connecting as ConnectingIcon3,
  Linking as LinkingIcon3,
  Bonding as BondingIcon3,
  Attaching as AttachingIcon3,
  Fastening as FasteningIcon2,
  Securing as SecuringIcon5,
  Locking as LockingIcon3,
  Closing as ClosingIcon2,
  Sealing as SealingIcon3,
  Finishing as FinishingIcon2,
  Completing as CompletingIcon2,
  Ending as EndingIcon2,
  Concluding as ConcludingIcon2,
  Terminating as TerminatingIcon2,
  Stopping as StoppingIcon2,
  Halting as HaltingIcon2,
  Pausing as PausingIcon2,
  Resting as RestingIcon2,
  Relaxing as RelaxingIcon2,
  Unwinding as UnwindingIcon2,
  Calming as CalmingIcon2,
  Soothing as SoothingIcon2,
  Comforting as ComfortingIcon2,
  Reassuring as ReassuringIcon2,
  Encouraging as EncouragingIcon2,
  Motivating as MotivatingIcon2,
  Inspiring as InspiringIcon2,
  Uplifting as UpliftingIcon2,
  Elevating as ElevatingIcon2,
  Raising as RaisingIcon2,
  Lifting as LiftingIcon2,
  Boosting as BoostingIcon2
} from 'lucide-react';
import { NavLink, useLocation } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';

interface MenuItem {
  title: string;
  icon: React.ComponentType<any>;
  href: string;
  roles: string[];
}

export const Sidebar = () => {
  const { hasRole } = useAuth();
  const location = useLocation();

  const menuItems: MenuItem[] = [
    // Dashboard items - pisahkan berdasarkan role
    {
      title: 'Dashboard Admin',
      icon: Home,
      href: '/admin-dashboard',
      roles: ['admin', 'waka_kesiswaan'],
    },
    {
      title: 'Dashboard Siswa',
      icon: Home,
      href: '/student-dashboard',
      roles: ['siswa'],
    },
    {
      title: 'Dashboard Wali Kelas',
      icon: Users,
      href: '/homeroom-dashboard', 
      roles: ['wali_kelas'],
    },
    
    // Student specific entries
    {
      title: 'Presensi Harian',
      icon: Clock,
      href: '/attendance/self',
      roles: ['siswa'],
    },
    {
      title: 'Rekap Presensi',
      icon: BarChart3,
      href: '/attendance/recap',
      roles: ['siswa'],
    },
    {
      title: 'Tambah Prestasi',
      icon: Trophy,
      href: '/achievements/submit',
      roles: ['siswa'],
    },
    {
      title: 'Laporan Kasus',
      icon: MessageSquare,
      href: '/cases/reports',
      roles: ['siswa'],
    },
    {
      title: 'Permohonan Izin',
      icon: PlusSquare,
      href: '/permits',
      roles: ['siswa'],
    },
    {
      title: 'Proposal Kegiatan',
      icon: ClipboardList,
      href: '/proposals',
      roles: ['siswa'],
    },
    {
      title: 'Pengajuan Surat',
      icon: FileText,
      href: '/documents',
      roles: ['siswa'],
    },
    
    // General management activities
    {
      title: 'Manajemen Presensi',
      icon: ListChecks,
      href: '/attendance/record',
      roles: ['admin', 'wali_kelas', 'guru_bk', 'tppk'],
    },
    {
      title: 'Permohonan Izin',
      icon: PlusSquare,
      href: '/permits',
      roles: ['admin', 'wali_kelas'],
    },
    
    // Management modules for admin
    {
      title: 'Manajemen Siswa',
      icon: Users,
      href: '/student-management',
      roles: ['admin', 'wali_kelas', 'guru_bk'],
    },
    {
      title: 'Manajemen Pelanggaran',
      icon: ShieldAlert,
      href: '/violations',
      roles: ['admin', 'tppk', 'guru_bk', 'wali_kelas'],
    },
    {
      title: 'Manajemen Prestasi',
      icon: Trophy,
      href: '/achievements',
      roles: ['admin', 'wali_kelas', 'guru_bk'],
    },
    {
      title: 'Manajemen Kasus',
      icon: MessageSquare,
      href: '/cases',
      roles: ['admin', 'tppk', 'arps', 'p4gn', 'guru_bk'],
    },
    {
      title: 'Ekstrakurikuler',
      icon: BookOpen,
      href: '/extracurricular',
      roles: ['admin', 'siswa', 'koordinator_ekstrakurikuler'],
    },
    {
      title: 'Jurnal Perwalian',
      icon: FileText,
      href: '/homeroom',
      roles: ['admin', 'wali_kelas'],
    },
    {
      title: 'Konseling BK',
      icon: GraduationCap,
      href: '/counseling',
      roles: ['admin', 'siswa', 'guru_bk'],
    },
    {
      title: 'Proposal Kegiatan',
      icon: ClipboardList,
      href: '/proposals',
      roles: ['admin', 'waka_kesiswaan', 'koordinator_ekstrakurikuler'],
    },
    {
      title: 'Laporan & Analitik',
      icon: BarChart3,
      href: '/reports',
      roles: ['admin', 'waka_kesiswaan', 'kepala_sekolah'],
    },
    {
      title: 'AI Management',
      icon: Zap,
      href: '/ai-management',
      roles: ['admin'],
    },
    {
      title: 'Sistem Notifikasi',
      icon: Bell,
      href: '/notifications',
      roles: ['admin', 'waka_kesiswaan'],
    },
    
    // Admin specific - lengkapi semua menu admin
    {
      title: 'Master Data',
      icon: Database,
      href: '/master-data',
      roles: ['admin'],
    },
    {
      title: 'Kelola Lokasi Presensi',
      icon: MapPin,
      href: '/attendance/location',
      roles: ['admin'],
    },
    {
      title: 'Pengaturan Jadwal Presensi',
      icon: CalendarClock,
      href: '/attendance/schedule',
      roles: ['admin'],
    },
    {
      title: 'Manajemen Pengguna',
      icon: UserPlus,
      href: '/user-management',
      roles: ['admin'],
    },
    {
      title: 'Manajemen Dokumen',
      icon: FolderOpen,
      href: '/documents',
      roles: ['admin'],
    },
    {
      title: 'Repository Dokumen',
      icon: Archive,
      href: '/document-repository',
      roles: ['admin'],
    },
    {
      title: 'Audit Trail & Log',
      icon: Activity,
      href: '/audit-logs',
      roles: ['admin'],
    },
    {
      title: 'Backup & Maintenance',
      icon: HardDrive,
      href: '/backup-maintenance',
      roles: ['admin'],
    },
    {
      title: 'Konfigurasi Sistem',
      icon: Settings,
      href: '/system-config',
      roles: ['admin'],
    },
    {
      title: 'Template Manager',
      icon: FileText,
      href: '/template-manager',
      roles: ['admin'],
    },
    {
      title: 'Status Sistem',
      icon: Monitor,
      href: '/system-status',
      roles: ['admin'],
    },
    {
      title: 'Analitik Lanjutan',
      icon: TrendingUp,
      href: '/advanced-analytics',
      roles: ['admin', 'kepala_sekolah'],
    },
    {
      title: 'Export Data',
      icon: Download,
      href: '/export-data',
      roles: ['admin'],
    },
    {
      title: 'Import Data',
      icon: Upload,
      href: '/import-data',
      roles: ['admin'],
    },
    {
      title: 'Pencarian Global',
      icon: Search,
      href: '/global-search',
      roles: ['admin'],
    },
    {
      title: 'Verifikasi Prestasi',
      icon: CheckCircle,
      href: '/achievement-verification',
      roles: ['admin', 'wali_kelas', 'guru_bk'],
    },
    {
      title: 'Poin Disiplin',
      icon: Target,
      href: '/discipline-points',
      roles: ['admin', 'wali_kelas', 'guru_bk', 'tppk'],
    },
    
    // Settings
    {
      title: 'Profil Saya',
      icon: User,
      href: '/profile',
      roles: ['admin', 'wali_kelas', 'guru_bk', 'siswa', 'koordinator_ekstrakurikuler', 'tppk', 'waka_kesiswaan'],
    },
    {
      title: 'Pengaturan',
      icon: Settings,
      href: '/settings',
      roles: ['admin'],
    },
    {
      title: 'Keluar',
      icon: LogOut,
      href: '/logout',
      roles: ['admin', 'wali_kelas', 'guru_bk', 'siswa', 'koordinator_ekstrakurikuler', 'tppk', 'waka_kesiswaan'],
    },
  ];

  const filteredMenuItems = menuItems.filter(item => {
    if (item.href === '/logout') {
      return true;
    }
    return item.roles.some(role => hasRole(role as any));
  });

  return (
    <div className="flex flex-col h-full bg-gradient-to-b from-blue-50 to-indigo-50 border-r border-blue-200 py-4">
      <div className="px-4 mb-6">
        <div className="flex items-center space-x-3">
          <img 
            src="/lovable-uploads/b258db0b-54a9-4826-a0ce-5850c64b6fc7.png" 
            alt="Logo SMKN 1 Kendal" 
            className="h-10 w-10 rounded-full shadow-md"
          />
          <div>
            <h2 className="font-bold text-blue-900 text-lg">Si-Kaji</h2>
            <p className="text-xs text-blue-600 font-medium">SMK N 1 Kendal</p>
          </div>
        </div>
      </div>
      
      <div className="space-y-1 flex-1 px-2">
        {filteredMenuItems.map((item) => (
          <NavLink
            key={item.title}
            to={item.href}
            className={({ isActive }) =>
              `flex items-center px-3 py-2.5 text-sm font-medium rounded-lg transition-all duration-200 group hover:bg-blue-100 hover:text-blue-700 ${
                isActive 
                  ? 'bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-lg scale-105' 
                  : 'text-gray-700 hover:scale-102'
              }`
            }
          >
            <item.icon className="h-4 w-4 mr-3 group-hover:scale-110 transition-transform" />
            <span className="truncate">{item.title}</span>
          </NavLink>
        ))}
      </div>
      
      <div className="px-4 pt-4 border-t border-blue-200">
        <p className="text-xs text-blue-600 text-center font-medium">
          Sistem Kesiswaan Terpadu
        </p>
      </div>
    </div>
  );
};
